root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/server.exe"
  cmd = "go build -o ./tmp/server.exe ."
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test\\.go"]
  include_ext = ["go", "toml", "env"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true
